language: php
before_script:
  - curl -O http://getcomposer.org/composer.phar
  - php composer.phar install --dev
php:
  - 7.0
script: 
  - vendor/bin/phing testi
after_success:
  - bash <(curl -s https://codecov.io/bash)
